from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('cart/', views.view_cart, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update-cart/<int:cart_item_id>/', views.update_cart, name='update_cart'),
    path('remove-from-cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_placed/<int:order_id>/', views.order_placed, name='order_placed'),
    path('cancel-order/<int:order_id>/', views.cancel_it, name='cancel_it'),
    path('request_return/<int:order_id>/', views.request_return, name='request_return'),
    path('order-history/', views.order_history, name='order_history'),
    path('order-detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('custom-admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('custom-admin/manage-products/', views.manage_products, name='manage_products'),
    path('custom-admin/add-product/', views.add_product, name='add_product'),
    path('custom-admin/update-product/<int:product_id>/', views.update_product, name='update_product'),
    path('custom-admin/delete-product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('custom-admin/manage-categories/', views.manage_categories, name='manage_categories'),
    path('custom-admin/add-category/', views.add_category, name='add_category'),
    path('custom-admin/update-category/<int:category_id>/', views.update_category, name='update_category'),
    path('custom-admin/delete-category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('custom-admin/manage-orders/', views.manage_orders, name='manage_orders'),
    path('custom-admin/update-order-status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('custom-admin/manage-users/', views.manage_users, name='manage_users'),
    path('custom-admin/promote-to-staff/<int:user_id>/', views.promote_to_staff, name='promote_to_staff'),
    path('custom-admin/delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('product-search/', views.product_search, name='product_search'),
]
