# Generated by Django 5.0.6 on 2024-07-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
