# Generated by Django 5.0.6 on 2024-07-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingStore', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
